<a href="https://colab.research.google.com/github/adityaiyer7/Prometheus/blob/master/PyTorchStuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
randint = torch.randint(-100, 100, (6,)) #from -100 to 100, and 6 numbers
print(randint)

tensor([ -9, -85,  62, -91, -74,   4])


In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input = torch.empty(2,3)
input

tensor([[-1.6668e+10,  3.1110e-41, -2.1806e+10],
        [ 3.1110e-41,  4.4842e-44,  0.0000e+00]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [12]:
linespace = torch.linspace(start = 3,end = 10,steps=5) #we go from 3 to 10, over 5 steps (adding the same amount everytime to get 5 values from 3 to 10)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[5, 0, 0],
        [0, 0, 1]])