<a href="https://colab.research.google.com/github/adityaiyer7/Prometheus/blob/master/PyTorchStuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,)) #from -100 to 100, and 6 numbers
print(randint)

tensor([ 23, -98,  92,  69, -42,  17])


In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[-4.5219e-30,  4.3820e-41,  1.4897e+04],
        [ 3.3232e-41,  1.4013e-45,  0.0000e+00]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linespace = torch.linspace(start = 3,end = 10,steps=5) #we go from 3 to 10, over 5 steps (adding the same amount everytime to get 5 values from 3 to 10)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[    101870389210732,                   0,                   1],
        [6066685341899685888,                  80,                  80]])

In [17]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,2, bias = False)
print("Linear weight:", linear.weight)
linear_one = nn.Linear(2,1, bias = 5.4)
print("Linear_one weight:", linear_one.weight)
#linear stands for linear transformation
#y = (weight*x) + bias
#https://pytorch.org/docs/stable/nn.html
print(linear_one(linear(sample)))

Linear weight: Parameter containing:
tensor([[-0.3518, -0.0057,  0.1946],
        [-0.1162, -0.3444, -0.0016]], requires_grad=True)
Linear_one weight: Parameter containing:
tensor([[-0.4523, -0.5444]], requires_grad=True)
tensor([3.7615], grad_fn=<ViewBackward0>)


In [18]:
import torch.nn.functional as F
tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1, dim = 0)
print(softmax_output)
#here's how the softmax function works: https://en.wikipedia.org/wiki/Softmax_function
#softmax([1,2,3])

#Step 1: e^1 = 2.71
#Step 2: 2.71^2 = 7.34
#Step 3: 2.71^3 = 19.9

#Step 4: 2.71+7.34+19.9 = 29.95
#Step 5: x = 2.71/29.95, y = 7.34/29.95, z = 19.9/29.95
#Step 6: [x,y,z]

tensor([0.0900, 0.2447, 0.6652])
